---
- name: storage clean | remove ceph repo files
  file:
    path: "/etc/apt/sources.list.d/download_ceph_com_debian_{{ ceph_version }}.list"
    state: absent
  when: ansible_os_family == "Debian"

- name: storage clean | remove ceph-common package
  apt:
    name: ceph-common
    autoremove: yes
    state: absent
  when: ansible_os_family == "Debian"

